obj-m += mod1.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

test:
	sudo dmesg -C
	sudo insmod mod1.ko
	cat /proc/mod1
	sudo rmmod mod1
	sudo dmesg